ALTER TABLE orders ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE hotel_bookings ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE order_items ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE inventory_locks ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE payment_transactions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE refunds ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE bookings ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
