ALTER TABLE orders MODIFY customer_phone VARCHAR(512) NULL;
ALTER TABLE hotel_bookings MODIFY phone VARCHAR(512) NULL;

ALTER TABLE shared_routes ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE travel_questions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE comments ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
